before_install:
  - sudo apt-get update
  #expect is required for testing genpass
  #xvfb, xclip and notify* are required for testing getpass
  - sudo apt-get install -y build-essential expect xclip notify-osd libnotify-bin
script: make test
